[2025-05-02 23:42:31,410:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:42:31,421:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:45:12,531:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:45:12,533:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:56:04,365:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:56:04,368:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:56:45,109:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:56:45,112:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:58:04,723:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:58:04,725:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-02 23:58:10,869:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-02 23:58:10,871:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:06,728:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:00:06,730:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:56,027:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:00:56,038:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:00:56,040:INFO:5(module)s:created directory at: artifacts]
[2025-05-03 00:00:56,042:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-03 00:02:41,333:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-03 00:02:41,336:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-03 00:02:41,338:INFO:5(module)s:created directory at: artifacts]
[2025-05-03 00:02:41,340:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-03 00:02:43,567:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C374:092A:131CEC:2B4F16:68150FCA
Accept-Ranges: bytes
Date: Fri, 02 May 2025 18:32:43 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4747-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746210762.464558,VS0,VE1092
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: eca38de1bc79563968077b993a94e273e6407242
Expires: Fri, 02 May 2025 18:37:43 GMT
Source-Age: 1

]
[2025-05-04 21:15:09,787:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:15:09,788:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:15:39,701:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:15:39,702:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:41:47,069:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:41:47,070:ERROR:5(module)s:'DataIngestionTrainingPipeline' object has no attribute 'main']
Traceback (most recent call last):
  File "C:\Users\MONISH\OneDrive\Documents\Data_science 2024\CNN_classifier\CNN_Classifier\main.py", line 8, in <module>
    obj.main()
    ^^^^^^^^
AttributeError: 'DataIngestionTrainingPipeline' object has no attribute 'main'
[2025-05-04 21:45:00,567:INFO:5(module)s:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-04 21:45:00,579:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 21:45:00,591:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 21:45:00,592:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 21:45:00,593:INFO:5(module)s:created directory at: artifacts/data_ingestion]
[2025-05-04 21:45:02,694:INFO:5(module)s:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F606:08E7:F3191:2FDB4B:68179282
Accept-Ranges: bytes
Date: Sun, 04 May 2025 16:15:02 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4733-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1746375301.231853,VS0,VE905
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f498847570d42fc34d09c358c731b37fb0a9b647
Expires: Sun, 04 May 2025 16:20:02 GMT
Source-Age: 1

]
[2025-05-04 21:45:03,173:INFO:5(module)s:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-04 23:11:20,916:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:11:20,919:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:11:20,921:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:11:41,720:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:11:41,723:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:11:41,724:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:12:38,621:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:12:38,624:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:12:38,625:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:13:39,029:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:13:39,032:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:13:39,033:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:15:18,609:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:15:18,612:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:15:18,614:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:15:18,615:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-04 23:15:19,163:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:15:19,386:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:19:09,570:INFO:5(module)s:yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:19:09,574:INFO:5(module)s:yaml file: params.yaml loaded successfully]
[2025-05-04 23:19:09,576:INFO:5(module)s:created directory at: artifacts]
[2025-05-04 23:19:09,578:INFO:5(module)s:created directory at: artifacts/prepare_base_model]
[2025-05-04 23:19:10,012:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-04 23:19:10,216:WARNING:5(module)s:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
